### PR TITLE
fixed navbar problem

### LINKED ISSUE #24: rebuild the navbar

### PR DESCRIPTION
**Pull request by SeifEleslam**
Fixing the floating issue of navbar

### CODE REVIEW

File: frontend/src/components/Navbar.jsx [hunk 1]
```diff
@@ -13,29 +13,27 @@ const Navbar = () => {
...
+        <button
+          onClick={toggleMenu}
+          type="button"
+          className="bg-transparent border border-white text-white hover:bg-white hover:text-gray-800 px-3 py-2 rounded-md lg:hidden"
+        >
+          {isOpen ? 'X' : 'Menu'}
+        </button>
+      </div>
+      <NavbarMenu isOpen={isOpen} routes={ROUTES} setIsOpen={setIsOpen} />
+    </nav>
```
Comment (Ameer2000Mzori) [inline frontend/src/components/Navbar.jsx:36]: good job i like this!!!

**Review by Ameer2000Mzori — APPROVED** [review]
good job
